## **Numpy**

- NUMERICAL PYTHON
- POWERFUL N-DIMENSIONAL ARRAYS

    Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.
- NUMERICAL COMPUTING TOOLS

    NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.
- OPEN SOURCE
- EASY TO USE

    NumPy’s high level syntax makes it accessible and productive for programmers from any background or experience level.


In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [3]:
#check version
np.__version__

'1.23.5'

##Creation of arrays using numpy

In [4]:
a = [10,20,30,40]
a

[10, 20, 30, 40]

np.array(data,dtype)

In [5]:
np.array(a)

array([10, 20, 30, 40])

In [6]:
np.array(a) * 100

array([1000, 2000, 3000, 4000])

##numpy peforms element by element operations

In [8]:
# if we want to change data type then use dtype
np.array(a,dtype=float)

array([10., 20., 30., 40.])

In [9]:
# implicite typecasting
np.array([1,2,3,4.])

array([1., 2., 3., 4.])

In [10]:
# numpy array using range()
np.array(range(1,5))

array([1, 2, 3, 4])

In [11]:
# check properties of numpy array
x = np.array(range(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#check dimension
x.ndim

1

In [13]:
#check total elemnts present
x.size

10

In [15]:
# check data type
x.dtype

dtype('int64')

In [16]:
# check for rows and column records
x.shape

(10,)

In [18]:
# lets create 2D array
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
y.ndim

2

In [20]:
y.shape

(3, 3)

In [21]:
y.size

9

In [22]:
y.dtype

dtype('int64')

In [24]:
# 3D array
z = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
z

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
z.shape

(2, 2, 2)

In [26]:
z.ndim

3

In [27]:
z.size

8