## **Statistical Mathematical operations**

# **Sum()**

In [1]:
import numpy as np

In [2]:
x = np.array([[2,3,4],[5,6,7],[8,9,10]])
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
np.sum(x)  # addition of all the elements

54

In [5]:
x.sum()

54

In [6]:
sum(x) #columnwise addition

array([15, 18, 21])

In [7]:
x.sum(axis=1) #row-wise addition


array([ 9, 18, 27])

In [8]:
x.sum(axis=0) #column-wise addition

array([15, 18, 21])

### mean(): average of numbers



In [9]:
# average= sumof all numbers/count of numbers
x.sum()/x.size

6.0

In [10]:
x.mean()

6.0

In [11]:
x.mean(axis=1) # row wise avg


array([3., 6., 9.])

In [12]:
x.mean(axis=0) # column wise avg

array([5., 6., 7.])

# standard deviation

In [14]:
np.std(x)

2.581988897471611

In [15]:
x.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [16]:
x.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

# Operations over numpy array

In [19]:
a = np.random.random((3,3))
a

array([[0.52060651, 0.53477645, 0.25540548],
       [0.70060443, 0.71239425, 0.88718471],
       [0.13286935, 0.33597043, 0.11994544]])

In [20]:
#add 1000 in each number
#elementwise addition
np.add(a,1000)

array([[1000.52060651, 1000.53477645, 1000.25540548],
       [1000.70060443, 1000.71239425, 1000.88718471],
       [1000.13286935, 1000.33597043, 1000.11994544]])

In [21]:
a + 1000

array([[1000.52060651, 1000.53477645, 1000.25540548],
       [1000.70060443, 1000.71239425, 1000.88718471],
       [1000.13286935, 1000.33597043, 1000.11994544]])

In [22]:
a #all above ops are temp., they are not chaning original array

array([[0.52060651, 0.53477645, 0.25540548],
       [0.70060443, 0.71239425, 0.88718471],
       [0.13286935, 0.33597043, 0.11994544]])

In [23]:
#x**2
np.power(x,3)

array([[   8,   27,   64],
       [ 125,  216,  343],
       [ 512,  729, 1000]])

In [24]:
p = np.array([[10,20],[30,40]])
p

array([[10, 20],
       [30, 40]])

In [25]:
q = np.array([[1,2],[4,5]])
q

array([[1, 2],
       [4, 5]])

In [26]:
p + q   #addition of 2 arrays using operator: element by element addition

array([[11, 22],
       [34, 45]])

In [28]:
np.add(p,q) #addition of 2 arrays using add method of numpy

array([[11, 22],
       [34, 45]])