# **np.resize(): permenant conversion**

Return a new array with the specified shape.



In [4]:
import numpy  as np

In [5]:
np.resize?

In [7]:
b = np.arange(24)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
# convert b array to 2D
b.resize(3,8)

In [9]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [11]:
b.shape

(3, 8)

# np.reshape(): temp conversion of shape

Gives a new shape to an array without changing its data.

In [12]:
np.reshape?

In [13]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [14]:
b.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [15]:
b.size

24

In [16]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [17]:
b.reshape(6,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [18]:
b.shape

(3, 8)

# **np.ravel()**

Return a contiguous flattened array

In [19]:
np.ravel?

In [20]:
# using ravel we can convert nd array to 1D array (Temp.)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [21]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# np.flatten()

Return a contiguous flattened array.

In [24]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

# **difference between ravel() and flatten()**

-Return only reference/view of the original array
-If you modify the array you would notice that the value of the original array also changes.

-Ravel is faster than flatten() as it does not occupy any memory.

-Ravel is a library-level function.



flatten()


-Return copy of the original array
-If you modify any value of this array value of the original array is not affected.

-Flatten() is comparatively slower than ravel() as it occupies memory.

-Flatten is a method of an ndarray object. Let us check out the difference in this code.