##Explore different ways of creating numpy array

## **np.arange**

Return evenly spaced values within a given interval.

In [3]:
import numpy as np
# exactly same as that of range in python
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [5]:
np.arange(3,7)

array([3, 4, 5, 6])

In [6]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## **np.random()**

 Return random floats in the half-open interval [0.0, 1.0).

In [8]:
np.random.random(5)

array([0.76870642, 0.96392438, 0.11880466, 0.22016653, 0.83404927])

In [9]:
np.random.random((4,5))

array([[0.64851641, 0.46500735, 0.59042662, 0.76651117, 0.92982156],
       [0.03023312, 0.35385832, 0.92975442, 0.48234276, 0.81263286],
       [0.74432035, 0.6977596 , 0.01597304, 0.11583002, 0.99056319],
       [0.2589033 , 0.34916774, 0.79122291, 0.6907782 , 0.74241385]])

In [10]:
np.random.random((3,2,2))

array([[[0.91413711, 0.0814674 ],
        [0.84801783, 0.42628661]],

       [[0.29001977, 0.27173545],
        [0.22459447, 0.57895734]],

       [[0.16071449, 0.13194489],
        [0.26632241, 0.57900003]]])

## **np.randint()**

randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

In [12]:
np.random.randint(low=2,high=13)

9

In [13]:
np.random.randint(low=2,high=13,size=6)

array([10,  7, 11, 11,  4,  8])

## **np.zeros()**
Return a new array of given shape and type, filled with zeros

In [15]:
np.zeros((3))

array([0., 0., 0.])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## **np.ones()**
Return a new array of given shape and type, filled with ones.


In [19]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

## **np.identity()**
Return the identity array.

The identity array is a square array with ones on
the main diagonal.

In [24]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#1. Create 4x4 array with all values set to True
np.ones((4,4),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
#2. Create 4x4 array with all values set to False
np.zeros((4,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [33]:
#3. Create 4x4 array with diagonal values set to True and Non diagonal False
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [34]:
#4. Create 4x4 array with diagonal values set to False and Non diagonal True
~np.identity(4,dtype=bool)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

## **np.full()**
Return a new array of given shape and type, filled with `fill_value`.


In [36]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [38]:
np.full((3,4,3),5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

## **np.random.randn()**
Return a sample (or samples) from the "standard normal" distribution.

means values bentwen range -3 to +3

In [39]:
np.random.randn(4)

array([-0.30589835, -0.34912   ,  1.82342632,  0.11564574])

In [41]:
np.random.randn(3,4)

array([[-0.38912121,  1.20114348, -0.68937017,  1.14739793],
       [ 0.49240889,  0.23069619, -0.17983705, -1.74801778],
       [ 1.72028996,  0.07206254, -0.64905835, -1.44864395]])

## create an empty array

In [42]:
np.array(None)

array(None, dtype=object)

In [43]:
np.array([])

array([], dtype=float64)

In [44]:
# what is a type of numpy array?
a = np.array([1,2,3,4])
type(a)

numpy.ndarray

## Create an array with same dimension and shape

In [46]:
a = np.random.random((3,3))
a

array([[0.09024025, 0.12122122, 0.45878722],
       [0.04086412, 0.8360259 , 0.25694593],
       [0.96802144, 0.75173782, 0.66308817]])

In [47]:
#np.ones_like
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
#np.zeros_like
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
# create an empty array with garbage values
np.empty_like(a)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])